format = """
$directory\
$username\
($c)\
($nodejs)\
($git_branch)\
($git_state)\
($git_status)\
($git_metrics)\
$time\
$cmd_duration\
$line_break\
$character
"""

add_newline = true

[username]
show_always = true
style_user = 'bold green'
format = '[$user]($style) '

[cmd_duration]
style = 'bold cyan'

[time]
disabled = false
style = "bold yellow"
format = "[$time]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false
